Resources:    
  AthenaPartitionerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-athena-partitioner
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonAthenaFullAccess
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: myPolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: # Gives permission to S3
                  - s3:PutObject
                  - s3:ListBucket
                  # - s3:GetBucketNotification
                  # - s3:PutBucketNotification
                Resource: 
                  - arn:aws:s3:::${self:custom.delivery-bucket-name}

  AthenaDatabase:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: ${self:custom.database-name}
        Description: Config snapshot database
      CatalogId: !Ref AWS::AccountId
    
  AthenaTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref AthenaDatabase
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: ${self:custom.table-name}
        TableType: EXTERNAL_TABLE
        PartitionKeys:
        - Name: dt
          Type: string
        - Name: region
          Type: string
        StorageDescriptor:
          Location:
            Fn::Join:
              - ''
              -
                - 's3://'
                - !Ref ConfigDeliveryBucket
                - '/AWSLogs'
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
          Columns:
            - Name: fileversion
              Type: string
            - Name: configSnapshotId
              Type: string
            - Name: configurationitems
              Type: array<struct<configurationItemVersion:string,configurationItemCaptureTime:string,configurationStateId:bigint,awsAccountId:string,configurationItemStatus:string,resourceType:string,resourceId:string,resourceName:string,ARN:string,awsRegion:string,availabilityZone:string,configurationStateMd5Hash:string,configuration:string,supplementaryConfiguration:map<string,string>,tags:map<string,string>,resourceCreationTime:string>>